info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /services

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
      
server:
  port: 8765

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2.console.enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.xyz.metallica.gateway: DEBUG